### ISSUE TITLE
Rich result metadata

### ISSUE THREAD

**Issue by jackcarey** [CanopusFalling/Queer-Calendar-Sheffield#39]
Add metadata to the site for event SEO. We can consider a sitelinks search and breadcrumbs once individual pages are in place.

**To-do:**

- [ ] `RichResult` component containing JSON-LD event metadata
- [ ] Sitelinks metadata
- [ ] Breadcrumbs metadata

**Links**

- [Events (Google)](https://developers.google.com/search/docs/appearance/structured-data/event)
- [Events (Bing)](https://www.bing.com/webmasters/help/?topicid=0f23328d)
- [Sitelinks Search (Google)](https://developers.google.com/search/docs/appearance/structured-data/sitelinks-searchbox)
- [Breadcrumbs (Google)](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb)

**Comment by CanopusFalling** [comment]
We could also pass a prop to the `eventCard` component to turn this kind of functionality on or off to avoid code reuse. Especially considering `eventList` is likely to be replaced with a more user friendly interface soon, see #24 for more information.

**Comment by jackcarey** [comment]
I've just doubled checked and Bing actually supports JSON-LD, though they don't document examples of it. A separate `eventCard` component is probably still worthwhile, but I'll limit this issue to the rich result stuff.

JSON-LD: https://json-ld.org/

**Comment by CanopusFalling** [comment]
Have added a pull request for the json-LD data. Gonna close this issue with that given at the moment we don't really have a need for breadcrumbs because we're not working with lots of nested pages and the site is already well linked. Likewise for the Sitelinks Search, that would entail adding an entire search feature to the site and we don't need that and again google has already indexed the site well enough.
